### PR TITLE
Feat: rename

### PR DESCRIPTION
**Pull request by timcadman**
## To test:
- Test dsTidyverse and dsTidyverse client at the same time
- Install dsTidyverse on server of choice using `install_github("molgenis/ds-tidyverse", ref = "feat/rename")`
- Install dsTidyverseClient locally using `install_github("molgenis/ds-tidyverse", ref = "feat/rename-client")`
- It is better to install rather than using `devtools::load_all` as I've had some issues passing the checks doing it this way.
- Run `devtools::check()`
- Code review
- Run this code: 

```
ds.rename(
  df.name = "mtcars",
  tidy_select = list(new_name_1 = mpg, new_name_2 = drat),
  newobj = "test",
  datasources = conns)
```

### CODE REVIEW

**Comment by timcadman** [comment]
Summary of discussion with Demetris:
- Consider reducing number of dependent packages and include in utils
- Do I need a string length disclosure check?

**Review by StuartWheater — COMMENTED** [review]
It is my understanding that the preferred location of "AggregateMethods" and "AssignMethods" lists are in the file "inst/DATASHIELD".

**Review by StuartWheater — COMMENTED** [review]
Add '^docs$' to '.Rbuildignore'

**Review by marikaris — APPROVED** [review]

**Comment by timcadman** [comment]
Superceded by PR #30

**Comment by timcadman** [comment]
Superceded by PR #30

**Pull request closed without merging**
